# Generated by Django 5.0 on 2023-12-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='made_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
